# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-19230-GCS/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7vx485tffg1157-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/gsaied/Desktop/old_rtl/fire5_squeeze
    /home/gsaied/Desktop/old_rtl/fire2_3_expand_1
    /home/gsaied/Desktop/old_rtl/fire8_expand1
    /home/gsaied/Desktop/old_rtl/fire4_squeeze
    /home/gsaied/Desktop/old_rtl/new_fire6_9_squeeze
    /home/gsaied/Desktop/old_rtl/new_fire6_expand3
    /home/gsaied/Desktop/old_rtl/fire8_expand3
    /home/gsaied/Desktop/old_rtl/fire4_5_expand3
    /home/gsaied/Desktop/old_rtl/fire3_squeeze
    /home/gsaied/Desktop/old_rtl/conv1
    /home/gsaied/Desktop/old_rtl/fire9_expand1
    /home/gsaied/Desktop/old_rtl/fire2_squeeze
    /home/gsaied/Desktop/old_rtl/fire7_expand3
    /home/gsaied/Desktop/old_rtl/fire9_expand3
    /home/gsaied/Desktop/old_rtl/fire4_5_expand1
    /home/gsaied/Desktop/old_rtl/fire2_3_expand3
    /home/gsaied/Desktop/old_rtl/conv10
    /home/gsaied/Desktop/old_rtl/fire6_squeeze
    /home/gsaied/Desktop/old_rtl/fire7_expand1
    /home/gsaied/Desktop/old_rtl/fire6_expand1
    /home/gsaied/Desktop/old_rtl/fire7_squeeze
  } {
      /home/gsaied/Desktop/old_rtl/fire5_squeeze/mac.sv
      /home/gsaied/Desktop/old_rtl/fire5_squeeze/fire5_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire5_squeeze/rom_fire5_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire5_squeeze/biasing_fire5_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand_1/rom_fire3_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand_1/rom_fire2_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand_1/biasing_fire2_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand_1/mac.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand_1/fire2_3_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand_1/biasing_fire3_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire8_expand1/rom_fire8_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire8_expand1/biasing_fire8_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire8_expand1/mac.sv
      /home/gsaied/Desktop/old_rtl/fire8_expand1/fire8_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire4_squeeze/fire4_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire4_squeeze/mac.sv
      /home/gsaied/Desktop/old_rtl/fire4_squeeze/rom_fire4_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire4_squeeze/biasing_fire4_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire4_squeeze/rom2_fire4_squeeze.sv
      /home/gsaied/Desktop/old_rtl/new_fire6_9_squeeze/mac.sv
      /home/gsaied/Desktop/old_rtl/new_fire6_9_squeeze/fire9Squeeze.sv
      /home/gsaied/Desktop/old_rtl/new_fire6_9_squeeze/biasing_fire8_squeeze.sv
      /home/gsaied/Desktop/old_rtl/new_fire6_9_squeeze/biasing_fire9Squeeze.sv
      /home/gsaied/Desktop/old_rtl/new_fire6_9_squeeze/squeeze_wrapper.sv
      /home/gsaied/Desktop/old_rtl/new_fire6_9_squeeze/rom_fire8_squeeze.sv
      /home/gsaied/Desktop/old_rtl/new_fire6_9_squeeze/fire8_squeeze.sv
      /home/gsaied/Desktop/old_rtl/interface_top/half_acc.sv
      /home/gsaied/Desktop/old_rtl/interface_top/nonsoftmax.sv
      /home/gsaied/Desktop/old_rtl/interface_top/ram_3d.sv
      /home/gsaied/Desktop/old_rtl/interface_top/SecondSharedMemory.sv
      /home/gsaied/Desktop/old_rtl/interface_top/temp.sv
      /home/gsaied/Desktop/old_rtl/interface_top/zynqnet.sv
      /home/gsaied/Desktop/old_rtl/interface_top/half_acc_array.sv
      /home/gsaied/Desktop/old_rtl/scripts/mac.sv
      /home/gsaied/Desktop/old_rtl/new_fire6_expand3/fire6_expand3.sv
      /home/gsaied/Desktop/old_rtl/new_fire6_expand3/biasing_fire6_expand3.sv
      /home/gsaied/Desktop/old_rtl/new_fire6_expand3/mac.sv
      /home/gsaied/Desktop/old_rtl/new_fire6_expand3/rom_fire6_expand3.sv
      /home/gsaied/Desktop/old_rtl/new_fire6_expand3/rom2_fire6_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire8_expand3/rom_fire8_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire8_expand3/fire8_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire8_expand3/mac.sv
      /home/gsaied/Desktop/old_rtl/fire8_expand3/biasing_fire8_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand3/biasing_fire4_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand3/wrapper_rom_fire4.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand3/rom_fire4_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand3/mac.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand3/wrapper_rom_fire5.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand3/biasing_fire5_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand3/rom2_fire4_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand3/rom2_fire5_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand3/fire4_5_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand3/rom_fire5_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire3_squeeze/mac.sv
      /home/gsaied/Desktop/old_rtl/fire3_squeeze/biasing_fire3_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire3_squeeze/fire3_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire3_squeeze/rom_fire3_squeeze.sv
      /home/gsaied/Desktop/old_rtl/conv1/rom.sv
      /home/gsaied/Desktop/old_rtl/conv1/biasing.sv
      /home/gsaied/Desktop/old_rtl/conv1/wrapper_image.sv
      /home/gsaied/Desktop/old_rtl/conv1/conv_mac.sv
      /home/gsaied/Desktop/old_rtl/conv1/conv1.sv
      /home/gsaied/Desktop/old_rtl/fire9_expand1/fire9_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire9_expand1/mac.sv
      /home/gsaied/Desktop/old_rtl/fire9_expand1/biasing_fire9_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire9_expand1/rom_fire9_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire2_squeeze/mac.sv
      /home/gsaied/Desktop/old_rtl/fire2_squeeze/rom_fire2_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire2_squeeze/biasing_fire2_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire2_squeeze/fire2_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire7_expand3/rom_fire7_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire7_expand3/mac.sv
      /home/gsaied/Desktop/old_rtl/fire7_expand3/wrapper_rom_fire7_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire7_expand3/biasing_fire7_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire7_expand3/rom2_fire7_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire7_expand3/fire7_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire9_expand3/mac.sv
      /home/gsaied/Desktop/old_rtl/fire9_expand3/biasing_fire9_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire9_expand3/fire9_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire9_expand3/rom_fire9_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand1/fire4_5_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand1/mac.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand1/rom_fire5_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand1/biasing_fire5_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand1/rom_fire4_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire4_5_expand1/biasing_fire4_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand3/fire2_3_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand3/biasing_fire3_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand3/rom2_fire3_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand3/wrapper_rom_fire2.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand3/rom_fire3_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand3/mac.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand3/biasing_fire2_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand3/rom2_fire2_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand3/rom_fire2_expand3.sv
      /home/gsaied/Desktop/old_rtl/fire2_3_expand3/wrapper_rom_fire3.sv
      /home/gsaied/Desktop/old_rtl/conv10/rom_conv10_1.sv
      /home/gsaied/Desktop/old_rtl/conv10/rom2_conv10_1.sv
      /home/gsaied/Desktop/old_rtl/conv10/mac.sv
      /home/gsaied/Desktop/old_rtl/conv10/rom2_conv10_2.sv
      /home/gsaied/Desktop/old_rtl/conv10/biasing_conv10_1.sv
      /home/gsaied/Desktop/old_rtl/conv10/wrapper_rom_conv10_2.sv
      /home/gsaied/Desktop/old_rtl/conv10/biasing_conv10_2.sv
      /home/gsaied/Desktop/old_rtl/conv10/conv10_1_2.sv
      /home/gsaied/Desktop/old_rtl/conv10/rom_conv10_2.sv
      /home/gsaied/Desktop/old_rtl/conv10/wrapper_rom_conv10_1.sv
      /home/gsaied/Desktop/old_rtl/fire6_squeeze/mac.sv
      /home/gsaied/Desktop/old_rtl/fire6_squeeze/rom2_fire6_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire6_squeeze/biasing_fire6_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire6_squeeze/rom_fire6_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire6_squeeze/fire6_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire7_expand1/fire7_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire7_expand1/mac.sv
      /home/gsaied/Desktop/old_rtl/fire7_expand1/biasing_fire7_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire7_expand1/rom_fire7_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire6_expand1/fire6_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire6_expand1/biasing_fire6_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire6_expand1/mac.sv
      /home/gsaied/Desktop/old_rtl/fire6_expand1/rom_fire6_expand1.sv
      /home/gsaied/Desktop/old_rtl/fire7_squeeze/mac.sv
      /home/gsaied/Desktop/old_rtl/fire7_squeeze/biasing_fire7_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire7_squeeze/rom_fire7_squeeze.sv
      /home/gsaied/Desktop/old_rtl/fire7_squeeze/fire7_squeeze.sv
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top zynqnet
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {./.Xil/Vivado-19230-GCS/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-19230-GCS/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
