# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gsaied/Desktop/old_rtl/fire4_expand3/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/gsaied/Desktop/old_rtl/fire4_expand3/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/gsaied/Desktop/old_rtl/fire4_expand3/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  /home/gsaied/Desktop/old_rtl/fire4_expand3/weights.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_127.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_3.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_40.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_67.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_79.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_49.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_24.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_60.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_36.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_70.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_102.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_69.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_26.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_44.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_111.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_83.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_87.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_59.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_39.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_16.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_93.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_73.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_101.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_32.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_30.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_1.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_75.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_64.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_107.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_50.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_55.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_112.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_12.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_98.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_126.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_28.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_8.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_116.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_65.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_45.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_88.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_22.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_106.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_62.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_82.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_113.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_6.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_48.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_123.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_11.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_34.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_122.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_94.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_71.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_77.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_105.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_51.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_54.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_117.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_97.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_17.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_37.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_15.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_23.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_82.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_58.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_110.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_128.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_53.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_10.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_4.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_17.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_96.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_101.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_66.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_74.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_102.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_31.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_61.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_108.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_76.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_29.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_86.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_114.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_92.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_124.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_43.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_88.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_45.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_109.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_38.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_81.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_11.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_90.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_33.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_7.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_105.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_57.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_14.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_54.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_97.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_125.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_21.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_49.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_71.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_27.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_106.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_78.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_35.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_7.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_18.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_116.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_68.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_120.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_121.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_25.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_93.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_46.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_117.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_63.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_50.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_89.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_20.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_42.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_85.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_72.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_52.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_95.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_75.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_103.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_119.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_3.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_91.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_100.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_32.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_14.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_109.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_128.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_34.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_22.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_65.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_18.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_57.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_110.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_69.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_46.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_26.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_62.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_77.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_80.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_28.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_60.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_1.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_85.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_113.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_125.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_89.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_42.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_53.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_90.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_70.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_10.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_30.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_36.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_8.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_73.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_19.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_99.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_115.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_39.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_56.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_79.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_13.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_107.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_96.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_124.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_84.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_21.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_64.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_41.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_118.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_47.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_121.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_104.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_4.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_24.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_6.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_67.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_81.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_27.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_19.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_43.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_86.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_126.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_41.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_84.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_112.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_92.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_2.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_118.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_48.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_119.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_120.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_35.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_78.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_13.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_111.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_99.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_127.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_47.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_56.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_9.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_58.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_15.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_94.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_2.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_25.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_9.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_51.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_72.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_20.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_68.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_100.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_63.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_114.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_122.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_37.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_108.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_23.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_87.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_115.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_123.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_52.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_83.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_40.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_66.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_91.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_31.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_61.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_74.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_44.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_103.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_5.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_5.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_12.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_80.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_95.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_38.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_33.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_104.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_76.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_55.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/file_fire4_expand3_98.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_29.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_16.mem
  /home/gsaied/Desktop/old_rtl/fire4_expand3/extend__file_fire4_expand3_59.mem
}
read_verilog -library xil_defaultlib -sv {
  /home/gsaied/Desktop/old_rtl/fire4_expand3/rom2_fire4_expand3.sv
  /home/gsaied/Desktop/old_rtl/fire4_expand3/rom_fire4_expand3.sv
  /home/gsaied/Desktop/old_rtl/fire4_expand3/wrapper_rom.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top wrapper_rom -part xc7vx690tffg1761-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef wrapper_rom.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file wrapper_rom_utilization_synth.rpt -pb wrapper_rom_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
